# Generated by Django 5.2.4 on 2025-07-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing'),
        ),
    ]
